# version: 2.1

# orbs:
#   node: circleci/node@5

# jobs:
#   build-and-test-vite:
#     executor: node/default
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: npm
#       - run:
#           name: Run linter
#           command: npm run lint  
#       - run:
#           name: Run tests
#           command: npm test  
#       - run:
#           name: Build the Vite app
#           command: npm run build
#       - run:
#           name: Install dependencies
#           command: npm install 

# workflows:
#   vite-client-pipeline:
#     jobs:
#       - build-and-test-vite






version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build_and_test_vite:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build the Vite app
          command: npm run build

workflows:
  vite_client_pipeline:
    jobs:
      - build_and_test_vite
