version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20.2
    steps: 
      - checkout
      - run: npm ci
      - run: npm test
      - run: npm run build

workflows:
  build-and-test:
    jobs:
      - build
